//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hangman.ECCI_Hangman {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ECCI_Hangman", ConfigurationName="ECCI_Hangman.ECCI_HangmanPort")]
    public interface ECCI_HangmanPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Hangman#Hangman#testFunction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string testFunction();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Hangman#Hangman#testFunction", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> testFunctionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Hangman#Hangman#listHighscores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] listHighscores();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Hangman#Hangman#listHighscores", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> listHighscoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Hangman#Hangman#startGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string startGame(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Hangman#Hangman#startGame", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> startGameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Hangman#Hangman#playLetter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string playLetter(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Hangman#Hangman#playLetter", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> playLetterAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ECCI_HangmanPortChannel : hangman.ECCI_Hangman.ECCI_HangmanPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ECCI_HangmanPortClient : System.ServiceModel.ClientBase<hangman.ECCI_Hangman.ECCI_HangmanPort>, hangman.ECCI_Hangman.ECCI_HangmanPort {
        
        public ECCI_HangmanPortClient() {
        }
        
        public ECCI_HangmanPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ECCI_HangmanPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECCI_HangmanPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECCI_HangmanPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string testFunction() {
            return base.Channel.testFunction();
        }
        
        public System.Threading.Tasks.Task<string> testFunctionAsync() {
            return base.Channel.testFunctionAsync();
        }
        
        public string[] listHighscores() {
            return base.Channel.listHighscores();
        }
        
        public System.Threading.Tasks.Task<string[]> listHighscoresAsync() {
            return base.Channel.listHighscoresAsync();
        }
        
        public string startGame(string name) {
            return base.Channel.startGame(name);
        }
        
        public System.Threading.Tasks.Task<string> startGameAsync(string name) {
            return base.Channel.startGameAsync(name);
        }
        
        public string playLetter(string name) {
            return base.Channel.playLetter(name);
        }
        
        public System.Threading.Tasks.Task<string> playLetterAsync(string name) {
            return base.Channel.playLetterAsync(name);
        }
    }
}
